### ISSUE TITLE
Please add a license document

### ISSUE THREAD

**Issue by Foxite** [fractalysis/buttplug-vst#2]
Currently the code in this repo is not allowed to be re-used. Please add a license document to allow this. If you don't know what license to choose, [this website](https://choosealicense.com/) contains a lot of very useful information.

**Comment by fractalysis** [comment]
da9b06a05fc876e522459e91704d34c18a8af5aa - Feel free to use the code for anything, and I will try my best to maintain the repo so pull requests are always welcome.
